//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

== Administration

When you install Apache Karaf Cave server, it provides a new CaveServerMBean.

This MBean use the following object name:

----
org.apache.karaf.cave:type=repository,name=*
----

Thanks to this MBean, using any JMX client (like jconsole for instance), you can do all actions as you can using the
`cave:*` commands:

* `void createRepository(String name, String location, boolean generateObr, boolean install) throws Exception;`
* `void destroyRepository(String name) throws Exception;`
* `void installRepository(String name) throws Exception;`
* `void uninstallRepository(String name) throws Exception;`
* `void populateRepository(String name, String url, boolean generateObr, String filter) throws Exception;`
* `void proxyRepository(String name, String url, boolean generateObr, String filter) throws Exception;`
* `void updateRepository(String name) throws Exception;`
* `void uploadArtifact(String repository, String artifactUrl, boolean generateObr) throws Exception;`